### ISSUE TITLE
HERE maps integration does not work

### ISSUE THREAD

**Issue by syjer** [alfio-event/alf.io#850]
looks like the app_id / app_code parameters are no more accepted for new accounts.

Will move to apiKey. Note: the current user of HERE maps must migrate their app_id/app_code to api_key

**Comment by syjer** [comment]
fixed

**Comment by Nico0302** [comment]
In which version will this issue be resolved? It was closed with the release of 2.0-M2-2001 but still persists in 2.0-M2-2004 (docker hub image).

**Comment by cbellone** [comment]
Thanks for pointing it out. The issue has been included in the changelog by mistake.
We have decided to release the current status as M3, ETA mid July
